const Images = {
    background: require('./assets/images/background.gif'),
    purpleMenu: require('./assets/images/purple_panel.png'),
    purpleButton: require('./assets/images/purple_button.png'),
    floor: require('./assets/images/floor_tile.png'),
    pipeCore: require('./assets/images/pipe_tile.png'),
    pipeTop: require('./assets/images/pipe_top.png'),
    scepter1: require('./assets/images/Wraith1.png'),
    scepter2: require('./assets/images/Wraith2.png'),
    scepter3: require('./assets/images/Wraith3.png'),
    scepter4: require('./assets/images/Wraith4.png'),
    scepter5: require('./assets/images/Wraith5.png'),
    scepter6: require('./assets/images/Wraith6.png'),
    scepter7: require('./assets/images/Wraith7.png'),
    scepter8: require('./assets/images/Wraith8.png'),
    scepter9: require('./assets/images/Wraith9.png'),
    scepter10: require('./assets/images/Wraith10.png'),
    scepter11: require('./assets/images/Wraith11.png'),
    scepter12: require('./assets/images/Wraith12.png'),
    coin1: require('./assets/images/coin/Gold_21.png'),
    coin2: require('./assets/images/coin/Gold_22.png'),
    coin3: require('./assets/images/coin/Gold_23.png'),
    coin4: require('./assets/images/coin/Gold_24.png'),
    coin5: require('./assets/images/coin/Gold_25.png'),
    coin6: require('./assets/images/coin/Gold_26.png'),
    coin7: require('./assets/images/coin/Gold_27.png'),
    coin8: require('./assets/images/coin/Gold_28.png'),
    coin9: require('./assets/images/coin/Gold_29.png'),
    coin10: require('./assets/images/coin/Gold_30.png'),
   
}

export default Images;